### ISSUE TITLE
Remove single book from recent books list

### ISSUE THREAD

**Issue by tuxor1337** [sufficientlysecure/document-viewer#111]
Via google-groups/sufficientlysecure-apps by user Patrick B.:

Thanks for a good pdf viewer. I would like to ask if there is a way to remove only one book from the recent book list without clearing the whole list? I hope that you would consider this as a new option in upcoming versions.

**Comment by pbrouty** [comment]
I found that there is a way provided. Long press on book to remove. Tap on "Clear recent data...". Then in next window, tap "Exclude from recents".

**Comment by tuxor1337** [comment]
Indeed ;)
