### ISSUE TITLE
Text blinking with 'fade in' (single page mode)

### ISSUE THREAD

**Issue by a--v--k** [sufficientlysecure/document-viewer#12]
https://code.google.com/p/ebookdroid/issues/detail?id=392

What steps will reproduce the problem?
1. set User interface\Brightness to 30%
2. set Rendering to 'Single page'
3. set Page transition to 'Fade in'
4. turn the page

What is the expected output?
the next page must brighten (fade out) from 0% brightness to 30% brightness

What do you see instead?
the next page brightens from 0% brightness to 100% brightness and then down to 30%. the page is 'blinking'

What version of the product are you using?
1.6.2

On what operating system?
4.1.1

Please provide any additional information below.
Blinking is very annoying when reading at night in 'Night mode'

**Comment by tuxor1337** [comment]
I thought about this and I think it's actually a bit picky, isn't it? You could simply disable the animation altogether, couldn't you?

**Comment by dschuermann** [comment]
@tuxor1337  Unfortunately, this issue has been imported from Googlecode by @a--v--k so I don't think the original author will answer.

**Comment by tuxor1337** [comment]
Oh right, and the original bug has been closed as "wontfix". Okay, so let's focus on more important stuff...
