### ISSUE TITLE
"Positive images in night mode" not working?

### ISSUE THREAD

**Issue by rolodato** [SufficientlySecure/document-viewer#122]
I am viewing this PDF with night-mode and "positive images in night-mode" enabled: http://gabriellacoleman.org/Coleman-Coding-Freedom.pdf

Here are my book settings:

![lopobqaufzyecvjsy_9omfrctujetejhfgwhbu-d-l-rgh2bxkzr2whv2_dtqun0uzoty4n800dxdb-kzsdbs5f7tw s1706](https://cloud.githubusercontent.com/assets/829698/9512412/eed31656-4c57-11e5-8812-0d32c6a73a6d.png)

On page 23 you can see an image that shows in negative:

![i-ngz4l6cce8cl8syawd6rcvhad0zqqaw7xwwaylkojnn-kfhhue8tp0tso5rqnmc08a8fqci315emiddnqeayvgns8 s1706](https://cloud.githubusercontent.com/assets/829698/9512422/11f71ace-4c58-11e5-93c6-c58436eddee2.png)

I am running v2.7.2 on a Moto X (2013) with Android 5.1.

**Comment by snelltheta** [comment]
I can confirm this bug in Version 2.7.3, too.

**Comment by ericwa** [comment]
Took a while, but tracked down and fixed in ffaf25a760e0b35fd646f65d371c053c25018dcf !
The feature is a bit of a hack, but it works on pdf's / epub's that I tested..

![screen](https://cloud.githubusercontent.com/assets/239161/19833042/88eef0c0-9df1-11e6-87ac-c049153ffd94.png)
