### ISSUE TITLE
Switching between the OPDS browser and Library View closes program

### ISSUE THREAD

**Issue by snelltheta** [SufficientlySecure/document-viewer#124]
By the use of the software back button in v2.7.3 in Lollipop on Nexus 7, the program closes once I do the following 1 or more times:
.Open program
.Open OPDS Browser via icon
.Press software back button

UPDATE: This also happens when exiting the file browser, accessed from the icon, then using back button to go back to Library view (suddenly closing the whole program).

**Comment by ericwa** [comment]
This was introduced by e7432ad3c6fb66de67e149488d21d4d769dff49c , I'll see if I can fix it
