### ISSUE TITLE
Merge "Fullscreen" and "Show Title"

### ISSUE THREAD

**Issue by ericwa** [SufficientlySecure/document-viewer#132]
Sorry, hit submit by accident before writing the description.

I suggest merging the "Fullscreen" and "Show Title" options, so being in fullscreen mode also hides the title (Action bar). Currently I find it cumbersome to have these as two separate options.

I think this would improve the usability of fullscreen mode, and also allow make document-viewer's UI closer to other Android reader apps that use a single tap to show/hide the system+app UI.

These Android docs mention "You should never show the action bar without the status bar", suggesting they should be linked:
https://developer.android.com/training/system-ui/status.html

**Comment by tuxor1337** [comment]
Your implementation is fine, I think.
