### ISSUE TITLE
MuPDF released 1.8

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [SufficientlySecure/document-viewer#133]
I got a news from MuPDF website that they produced a release candidate of version 1.8. This version have large improvement for EPUB support.

**Comment by ericwa** [comment]
I tried updating to the mupdf 1.8 RC in this branch: https://github.com/SufficientlySecure/document-viewer/compare/master...ericwa:update-mupdf

Ran in to a problem where none of my epub files were loading. Was able to work around it by removing `LOCAL_CFLAGS += -DNOCJK` from document-viewer's jni/mupdf/Core.mk. I think it might be a mupdf bug, so I reported it on their bug tracker:
http://bugs.ghostscript.com/show_bug.cgi?id=696326

Also, one hunks in nightmode_slowcmyk.patch that is applied to mupdf by init.sh failed to apply, haven't yet looked into fixing that.

**Comment by timofonic** [comment]
Any news?

**Comment by ericwa** [comment]
Looks like they released v1.8

**Comment by KrasnayaPloshchad** [comment]
> Looks like they released v1.8

OK, they released new version in 11 November, seen from their news page.

**Comment by timofonic** [comment]
Are there plans to support it? :)

**Comment by KrasnayaPloshchad** [comment]
> Are there plans to support it? :)

#144 is a pull request for updating the MuPDF library.

**Comment by ericwa** [comment]
Updated to 1.9a with https://github.com/SufficientlySecure/document-viewer/pull/182
