### ISSUE TITLE
Option: Always start PDF view at first page

### ISSUE THREAD

**Issue by sunyuyangg555** [SufficientlySecure/document-viewer#139]
I want to  show a PDF and always show the first page when I finish the ViewerActivity, what should I do?

**Comment by tuxor1337** [comment]
It's not clear to me, what you're asking for. Are you asking for a setting that says for a specific file that it should jump to the first page every time it's opened - independent of the page which has been viewed last time?

**Comment by sunyuyangg555** [comment]
yes , my english is bad . so sorry
