### ISSUE TITLE
Tap to toggle fullscreen?

### ISSUE THREAD

**Issue by ericwa** [SufficientlySecure/document-viewer#143]
Would there be interest in having a single tap on the middle of the page toggle fullscreen?
This would probably depend on my other suggestion to link "show title" to "fullscreen": https://github.com/SufficientlySecure/document-viewer/issues/132
 
The majority of reading apps I have installed do this (Drive PDF Viewer, Dropbox PDF Viewer, Google Play Books, Kindle), although "Google PDF Viewer" is an exception, it's always in fullscreen but the actionbar/statusbar/navigation buttons show/hide automatically when you scroll.

**Comment by hackerb9** [comment]
Yes, there is interest. It makes sense to behave the way most users will expect.

**Comment by ericwa** [comment]
Thanks for the feedback, I like this too and made a first attempt at implementing it.

**Comment by tuxor1337** [comment]
The implementation is fine, I think.
