### ISSUE TITLE
Restore a "force auto rotation" option

### ISSUE THREAD

**Issue by frazzmark** [SufficientlySecure/document-viewer#147]
I'm using slimrom 5.1.1. I locked the rotation on vertical using the quick toggle, but when I turn the screen the device screen rotates also.
I opened an issue here because this bug only happens

**Comment by frazzmark** [comment]
*sorry I touched the wrong button - here continues
This bug only happens with this app, with any other app  the screen doesn't rotate, it stays vertical

**Comment by ericwa** [comment]
I get this as well; the screen lock buttons in the document-viewer menu work, but when they are unchecked, the screen auto-rotates, even if the OS is set to locked

**Comment by ericwa** [comment]
I found a setting for this. Go to "All Settings -> Rendering -> Rotation Mode" and set it to "Unspecified'.
It looks like this setting controls the rotation mode in use when the Force Landscape/Portrait toolbar buttons are not checked.

There are a few things that could be done:
 - The default should probably be changed from Automatic to Unspecified (but this will only help people who do fresh installs)
 - That setting should be moved to the "User Interface" section of the settings UI rather than "Rendering"?
 - Do we even need this setting, given that the toolbar has force landscape / force portrait buttons?

**Comment by ericwa** [comment]
btw, the place where the default rotation mode is set to auto is here (pretty sure): https://github.com/SufficientlySecure/document-viewer/blob/master/document-viewer/src/main/java/org/ebookdroid/common/settings/definitions/AppPreferences.java#L40

**Comment by tuxor1337** [comment]
@ericwa Regarding your 3rd point: I think you don't need such a setting in later versions of Android. But document-viewer was designed at a very early stage of the Android operating system and the original author always made an effort for backwards compatibility. I would probably decide against backwards compatibility in this case and remove this setting from document-viewer altogether.

**Comment by ericwa** [comment]
@tuxor1337 That sounds better, so remove the "All Settings -> Rendering -> Rotation Mode" setting, but keep the "force portrait"/"force landscape" toolbar buttons?
I do find the toolbar buttons useful, especially "Force Landscape" which I wouldn't normally use outside of Document Viewer, but sometimes is how I want to hold my phone/tablet.
I'll look into it and make a new PR.

**Comment by ericwa** [comment]
I think 9eefa8a945dc1361640055337134a807552e2f8b addressed this issue

**Comment by lucamp** [comment]
Hi guys,
auto rotation for me was very important as it helped me read better without checking other application buttons or OS rotation button.
Is there a way to reimplement it into the setting, but with an option that explain better it's meaning?
for instace:

All settings -> Rendering -> always force auto rotation        slide Yes or No

However this should not bore others, so the toolbar buttons must have priority and this option must be unchecked (slide with No position) by default

Thanks
Luca

**Comment by ericwa** [comment]
Sure, it should be easy to restore a "force auto rotate" option. For now the best way would be an extra option under Book Settings -> Rotation Mode. I know it's a bit annoying to have it per book, probably the rotation mode should not be saved per book at all, but that's a separate issue I guess.
