### ISSUE TITLE
Opening Epub files from Downloads app gives a black screen

### ISSUE THREAD

**Issue by ericwa** [SufficientlySecure/document-viewer#149]
This happens with master as well as the Play Store build.

The same epub files work when opened though ES File Explorer, or from the document-viewer bookshelf. Maybe related to how files opened from the Downloads app use content:// rather than file:// URI's.

**Comment by ericwa** [comment]
I see the problem.. MuPdfDocument.open() is called with the filename "/data/data/org.sufficientlysecure.viewer/files/temp1170287438content", which is the temporary file that the epub was copied to.

mupdf doesn't realize that is an epub and tries to load it as a pdf:
```
12-02 14:27:30.019 20652-20912/org.sufficientlysecure.viewer E/libmupdf: error: cannot recognize version marker
12-02 14:27:30.019 20652-20912/org.sufficientlysecure.viewer E/libmupdf: warning: trying to repair broken xref
12-02 14:27:30.059 20652-20912/org.sufficientlysecure.viewer E/libmupdf: error: invalid key in dict
```
I guess this is partly mupdf's fault: its epub_recognize() function for detecting epub files isn't very good and only checks file extension or caller-supplied mime type.

Will try to come up with a workaround.

**Comment by hackerb9** [comment]
Does Android have libmagic for recognizing file types? If not, you can still do a quick test: if it's a zip archive and the first file is named mimetype, it's not a pdf. :) (By epub spec, mimetype must be first in the archive.) If you want to be completely certain it's an epub, just check the contents of mimetype.
