### ISSUE TITLE
What about merging efforts with Koreader? It shares many goals and it's quite multiplatform

### ISSUE THREAD

**Issue by timofonic** [SufficientlySecure/document-viewer#158]
Hello.

What about merging effforts with Koreader? It's a somewhat similar app that even supports more platforms.

I think your project looks quite promising, but I consider the Lua approach a lot better than using Java. Java portability is a lie and adds lots of overhead, LuaJIT seems a lot more lightweight approach and even more portable.

I would love to have a very multiplatform open source  app as document reader on all my platforms, supporting lots formats and the newest features out there. I know this is a pipe dream, but one can always dream.

I cross-posted this in Koreader repo...
https://github.com/koreader/koreader/issues/1739
Kind regards.

**Comment by ericwa** [comment]
The two projects already share mupdf/djvulibre, which is good. DV is a normal android app, Koreader is not, but is cross platform and written in lua.. I think they coexist happily but there isn't much sharing of efforts we can do, besides both benefiting from improvements in mupdf.

**Comment by dschuermann** [comment]
I have the same opinion as @ericwa . I don't see any more shared work here and I don't see any real arguments in your text why Lua should be favored. Java is the main language supported by Android's API. This project never had the goal to work on any desktop OS. There are other applications building upon mupdf with that goal.

**Comment by timofonic** [comment]
@dschuermann 

There are other apps, but the file format support and features aren't in one application. Too much fragmentation in FOSS makes incomplete projects, lacking manpower.

LUA can be very fast. I think FOSS tends to be multiplatform, not praying to a platform that is becoming closer at each release ;)

But it's okay :) 

Kind regards.
