### ISSUE TITLE
could I show PDF in fragment?

### ISSUE THREAD

**Issue by sunyuyangg555** [SufficientlySecure/document-viewer#159]
could I show PDF in fragment? if yes what should i do?

**Comment by tuxor1337** [comment]
What do you mean with fragment?

**Comment by sunyuyangg555** [comment]
This is my current needs of the project, my project navigation use is ToolbarManager, through different fragments switching function.To display the PDF, now only from fragments jump to VewerActivity.If I can display PDF in fragments (my project only need to display the PDF), can be more easily with other functional integration.
Such as I want to show the PDF to add other functions (such as at the top shows a chance to read the PDF), I have to modify ViewerActivity source.Of course, these are only my personal needs.
Thank you very much for your reply

**Comment by ericwa** [comment]
I think it's outside the scope of this project to make a Fragment subclass for viewing PDF's reusable by other applications, so I'll close this for now.

Maybe the PdfRenderer class introduced in Android 5.0 would be useful to you, see this sample app which displays it in a Fragment: https://github.com/googlesamples/android-PdfRendererBasic
