### ISSUE TITLE
German naming of "Book" or "Document"

### ISSUE THREAD

**Issue by matsimon** [SufficientlySecure/document-viewer#160]
Hello

I've been using Document Viewer and I much like it, however I recently realized there were still a couple of missing translations in german.

Now I'm not so familiar with the code but but the app itselfs is called document viewer yet calls most items Books. So before I have to replace a word again, what is your preference Book (Buch) or document (Dokument).

-- Mathieu

**Comment by ericwa** [comment]
document-viewer was forked from an app called EBookDroid, so the original branding was as an ebook reader, and that's where the bookshelf look and the "Book" terminology comes from.

I really don't know which to pick - the English text in the app uses "Book", so I guess stick to "Buch"?

**Comment by matsimon** [comment]
OK, I see the point. I hope to send in a pull request in the coming days sticking to Book in this case.
