### ISSUE TITLE
No autorepeat in scrolling with hardware keys

### ISSUE THREAD

**Issue by JohnVeness** [SufficientlySecure/document-viewer#164]
Something has changed negatively between versions 2.7.2 and 2.7.3 (obtained from f-droid) regarding scrolling using hardware keys, meaning e.g. volume keys, or physical keyboard keys on devices with slideout keyboard.

In 2.7.2 I could hold down, e.g. volume down, and the document would continue to scroll down. There would be an initial delay after the first scroll, then a shorter delay between each subsequent scroll down, just like how keyboard autorepeats work.

In 2.7.3, holding down volume down doesn't scroll at all until you release the key, and will only scroll one page. It will also reduce the volume, which didn't use to happen.

There was no changelog update for 2.7.3 so I'm not sure if this was intentional, or which commit(s) caused it.

**Comment by tuxor1337** [comment]
Probably due to commit 5e496b3

**Comment by JohnVeness** [comment]
Thanks. That commit seems to be post the release of 2.7.3, so wouldn't have caused this issue between 2.7.2 to 2.7.3. Looking at https://github.com/SufficientlySecure/document-viewer/compare/v2.7.2...v2.7.3 I'm guessing maybe commit e7432ad was the cause?

If commit 5e496b3 fixes the volume UI from appearing, maybe 2.7.4 could be released with that fix? I'd like to see the autorepeat coming back, though, as it was useful with long documents.

**Comment by ericwa** [comment]
I confirmed e7432ad3c6fb66de67e149488d21d4d769dff49c broke auto-repeat, and also caused the volume popup to appear. The previous commit 46faf920a615784aa3d87e55c518a10cc935d92f has auto-repeat for scrolling with the volume buttons, and no volume dialog popping up, on my nvidia shield tablet.

**Comment by ericwa** [comment]
This should be fixed by 063b346b70de6c192c7eb0d4f4d3460512344eee
