### ISSUE TITLE
Full Network Access permissions

### ISSUE THREAD

**Issue by pixelrust** [SufficientlySecure/document-viewer#169]
I think it'd be relevant to explain why Document Viewer needs Full Network Access permissions (I guess it relates to OPDS but I don't really know about that).
I added a question to the FAQs - can someone please answer it?
https://github.com/SufficientlySecure/document-viewer/wiki/FAQ

I'd also suggest to add a quick reference about this in the description page:
https://github.com/SufficientlySecure/document-viewer

(I'm new to contributing, please let me know if I'm doing this wrong)

**Comment by dschuermann** [comment]
In addition to OPDS, Document Viewer also needs network access when it opens a PDF file directly using a URL. Next time, please don't add a question directly to the FAQ without knowing the answer, this is not very helpful.
