### ISSUE TITLE
Good time for a release?

### ISSUE THREAD

**Issue by ericwa** [SufficientlySecure/document-viewer#174]
@SufficientlySecure/document-viewer-devs 
There are quite a few changes since the last release, including some UI design changes (tap to toggle fullscreen, starting to use Material theme, etc.) that would be good to get feedback on from users.

Let me know if there's anything I should do to help - update the changelog I guess?

**Comment by dschuermann** [comment]
hey @ericwa , yes update the changelog and increase the version. You can also create a new tag. F-Droid will automatically build that new tag if it uses the same format as the old git tags. To update the Google Play version, please ping me here :)

Great contributions as always, it's awesome to see this project being maintained. If I could help with infrastructure or other things, let me know!

**Comment by ericwa** [comment]
@dschuermann Thanks for the info, and happy to help, I enjoy this app a lot. :-)

I updated the changelog + version code and tagged the 2.7.4 release a few days ago, and the new build showed on F-Droid today and it seems to work fine. Whenever you have a chance to update the play store build would be great.

**Comment by dschuermann** [comment]
@ericwa I updated the version in Google Play. Should pop up soon.
