### ISSUE TITLE
Scrolling with hardware volume buttons causes beeps

### ISSUE THREAD

**Issue by JohnVeness** [SufficientlySecure/document-viewer#175]
2.7.4 has fixed a problem that was present in 2.7.3 where scrolling with the volume buttons would cause the volume UI to appear. Now, in 2.7.4, the volume UI does not appear, but my device does "beep" as if the volume is changing. As far as I can tell, the volume isn't changing, but still, my device beeps when using the volume keys to scroll in Document Viewer, which didn't happen in 2.7.2 for example.

**Comment by ericwa** [comment]
Thanks - I can reproduce this; I never noticed before since my phone is always on vibrate! Will look in fixing it.
