### ISSUE TITLE
Error:error: 'set_new_handler' is not a member of 'std'

### ISSUE THREAD

**Issue by ShreeshGarg** [SufficientlySecure/document-viewer#177]
Hi 

I am trying to run the code for DjVu, but getting the following error 

Error:error: 'set_new_handler' is not a member of 'std'. I am using android ndk r-11. Do I need to use any particular NDK version.

**Comment by ericwa** [comment]
I was using `android-ndk-r10e` on OS X and built without errors.

I'll try updating to r11. Sounds like r11 switched to clang as the preferred compiler, maybe this is a clang incompatibility.

**Comment by ericwa** [comment]
Ok: just did a successful ndk-build of current master ( 3c967077 ) with `android-ndk-r11c-darwin-x86_64.zip`.

Make sure to run `init.sh`, it applies some patches to the submodules. Actually, it looks like there is something related to std::set_new_handler in one of the patches:
```
jni/djvu/overrides/compatibility.patch
24: static void (*old_handler)() = std::set_new_handler(throw_memory_error);
27:-static void (*old_handler)() = std::set_new_handler(throw_memory_error);
28:+//static void (*old_handler)() = std::set_new_handler(throw_memory_error);
30: static void (*old_handler)() = set_new_handler(throw_memory_error);
```

**Comment by ericwa** [comment]
Closing this, feel free to reopen if you still have trouble building
