### ISSUE TITLE
Allow recoloring pages in addition to night mode

### ISSUE THREAD

**Issue by sixpointzero** [SufficientlySecure/document-viewer#188]
In addition to night mode, you should add a feature to recolor pages like [Zathura](https://pwmt.org/projects/zathura/) does.

Instead of black background and white text, one should be able to set a custom color for the background and the text.

**Comment by ericwa** [comment]
Yes agreed! I would like a sepia preset.

**Comment by ericwa** [comment]
Implemented basic support for this in a97560f
- Only a book setting for now
- Tint color is just multiplied by the rendered document

**Comment by sixpointzero** [comment]
Thanks!
