### ISSUE TITLE
Copy Selected text or Share it 

### ISSUE THREAD

**Issue by mulles** [SufficientlySecure/document-viewer#192]
I have tried hard to find this function - Copy Selected text or be able to Share  with other app -  , but wasn't able.

Thus, should I have missed it, please point me to it, and I will be more than happy to make a pull request for the FAQ. 

Otherwise this would be an enchancement request. Selecting and Copying text would be best. Sharing would be nice. Anyhow thx a lot already for reading this.

**Comment by ericwa** [comment]
Agree, this would be good to have. Looks like we already have a feature request https://github.com/SufficientlySecure/document-viewer/issues/93 ,so I'll close this issue.
