### ISSUE TITLE
Select/Copy

### ISSUE THREAD

**Issue by Rbagman** [SufficientlySecure/document-viewer#196]
I saw the low dev comment in a reply to annotation, but select/copy comes with most
Document viewers. I like this app, but I have to use Polaris.

**Comment by ericwa** [comment]
Yep, agree, we have an issue for this:
https://github.com/SufficientlySecure/document-viewer/issues/93

**Comment by KnIfER** [comment]
it is a dull project in that it can never Select { one single alone lonely niji yi un 1 } character,not untill this very universe become old enough to die.
:)
