### ISSUE TITLE
Follow links within document

### ISSUE THREAD

**Issue by dim-0** [SufficientlySecure/document-viewer#198]
Hi there,
not sure, whether I'm simply missing something, but I thought I just ask...
I'm using document viewer v2.7.5 as provided via F-Droid.
When using epub or pdf documents, I'm not able to follow hyperlinks that refer to anchors within the same document (e.g. "p275"). Maybe it's not implemented at all (even though they are displayed in blue colour), maybe it's because tapping the screen just toggles fullscreen, maybe I'm just too stupid (I hope not). However, I'd highly appreciate any help on this.
Thanks so much for such a great application!
Cheers

**Comment by ericwa** [comment]
Hi,
For epub, it's a missing feature in the library that implements our epub support:
http://bugs.ghostscript.com/show_bug.cgi?id=696002

In PDFs, they should work, though. I get transparent yellow rectangles rendered on top of the links. Sometimes I have to zoom in a bit to tap them accurately.

**Comment by ericwa** [comment]
epub were implemented in mupdf, and are working in DV as of  ffaf25a760e0b35fd646f65d371c053c25018dcf
