### ISSUE TITLE
PDF file renders with missing symbols; only displays properly in some applications

### ISSUE THREAD

**Issue by myBestSoftAndPref** [SufficientlySecure/document-viewer#200]
I did screenshot of single file:
http://imgur.com/a/juLNS
**first** screen display by **Document Viewer**
**second** screen display by **VuDroid** https://f-droid.org/repository/browse/?fdfilter=VuDroid&fdid=org.vudroid

You can see gaps instead some symbols.
There is file example http://rgho.st/85spjC2x7

**Comment by ericwa** [comment]
I'm afraid there's not much we can do, the mupdf android app 1.9 also displays this file wrong. However, it doesn't work in any other PDF viewers (acrobat, OS X preview.app, google drive) so I think the file is not a conformant pdf (probably doesn't have fonts embedded?) 

I'm not sure what VuDroid was doing to make it render correctly, maybe an older version of mupdf.

**Comment by myBestSoftAndPref** [comment]
You are wrong!
1. Sumatra PDF is open source PDF viewer and it display document correctly. http://www.sumatrapdfreader.org
2. Google Chrome build-in PDF viewer display it correctly http://imgur.com/a/wpwNl

**Comment by ericwa** [comment]
I think you should report it to the mupdf bug tracker: http://bugs.ghostscript.com/

It doesn't look correct in sumatrapdf for me:
<img width="807" alt="screen shot 2016-08-25 at 10 17 16 am" src="https://cloud.githubusercontent.com/assets/239161/17977040/5265ee86-6aad-11e6-84eb-4030241ac84c.png">

Firefox looks OK though.

**Comment by myBestSoftAndPref** [comment]
![src](http://imgur.com/a/2XFuq)

**Comment by myBestSoftAndPref** [comment]
I have posted issue.
http://bugs.ghostscript.com/show_bug.cgi?id=697068

Sorry for my bad English. Unfortunately I don't have permission for editing issue description. (:

**Comment by myBestSoftAndPref** [comment]
It seems to me that this issue have been fixed already:
https://bugs.ghostscript.com/show_bug.cgi?id=697068#c8

I checked .pdf file and it shows properly for me.
