### ISSUE TITLE
Choose default rotation mode

### ISSUE THREAD

**Issue by Daedalon** [SufficientlySecure/document-viewer#206]
Book Settings and All Settings > Rendering have options in common, like Split pages, Crop pages (auto) etc. Changing any of these settings in All Settings sets the default for new books. There's one very useful Book Setting missing here: Rotation mode.

On many phones the most comfortable way to read books is Force landscape. Because it's not possible to set this as a default, this has to be set manually for every new opened book.

Adding this option in All Settings is a nice improvement to the UX.

**Comment by ericwa** [comment]
Hmm, it looks like we had that setting and I removed it because it was causing an issue (defaulted to auto-rotate: https://github.com/SufficientlySecure/document-viewer/issues/147 ). Should be pretty easy to re-introduce.

**Comment by ericwa** [comment]
I reverted 9eefa8a945dc1361640055337134a807552e2f8b (which removed the setting 
"All Settings -> Rendering -> Rotation Mode"), then I changed the default App Setting to "Unspecified" (to keep issue #147 fixed)

So now what we have in order from highest precedence to lowest is: Book Setting, then App Setting, then OS Setting.

Book Setting and App Setting default to "unspecified", so the OS setting is used.

If you change the App Setting to something like "Reverse Landscape", that is used for all books that don't have their book setting on "unspecified", which is the default.

**Comment by Daedalon** [comment]
Sounds great, thanks! To clarify, for me the ideal would be to be able to set the App Setting to Landscape, and then be able to temporarily switch between Landscape and Reverse Landscape within a book. Hopefully I understood correctly that the new version makes this usage pattern possible.

**Comment by ericwa** [comment]
@Daedalon The part where you can set the App Setting to Landscape is implemented and will be in the next release.

https://github.com/SufficientlySecure/document-viewer/issues/208 isn't yet implemented, although you'll be able to select Reverse Landscape in the app settings, so it's possible but  just a bit cumbersome.

Do you think "Reverse" is valuable as a setting saved per-book? Personally I don't see much value in saving the rotation mode per book, because whether I'm using a phone / table portrait or landscape is more dependent on whether I'm sitting down, reading in bed, etc.

I wonder if the "Force portrait"/"Force landscape" (and the not yet added "Reverse") buttons in the toolbar menu would be more useful if they controlled the app setting.

**Comment by Daedalon** [comment]
@ericwa Great news. Setting for a "reverse" is something I'd like to use to switch back and forth without having to leave the book view.

The goal is to be able to hold the device the other way around so that you can get a good grip without any buttons getting pressed accidentally. When you adjust your position so that it'd be easier to hold the device the other way around, for example with the other hand, currently you can't because there's no reverse. A reverse that would be hidden outside the book menu would require you to interrupt your reading a bit more to go and find it within global settings, which again would become outdated as soon as you adjust your position.

My vision of the UI:

1. Tap the book to show the top bar
2. Tap the magnifying glass to show the display options, including Force portrait/landscape, Split pages, Crop pages (auto) etc.
3. Tap Reverse, which would be included in the list.

A logical place for this option is after the Force portrait/Landscape. It would likely make sense to disable (gray out) the option when neither of those is selected so that auto rotation would not get affected by this.

Regarding whether this would be a per-book or global app setting: either way works fine. Ideally these would affect all books in my case, but I switch between books much less often than reading positions, so the main thing is that the option is accessible immediately while reading a book.
