### ISSUE TITLE
Global option to disable volume key scrolling

### ISSUE THREAD

**Issue by Daedalon** [SufficientlySecure/document-viewer#207]
It's common to put background music playing while reading. However, by default Document Viewer overrides the hardware volume keys to not be available for adjusting the volume but to be used for scrolling. I have never had a situation when I'd have wanted to use volume keys for scrolling, but always for adjusting the volume, which now requires going away from the app and then back.

It'd be useful to have a global option to disable this behavior for example under All Settings > Taps, swipes and keys. The setting name could be "Volume keys scroll", with the additional text "Use volume keys for scrolling instead of adjusting the volume."

**Comment by ericwa** [comment]
Thanks for the suggestion, implemented in 1cf0643
