### ISSUE TITLE
Adding support for Android 7.0 Nougat

### ISSUE THREAD

**Issue by xiatianyu** [SufficientlySecure/document-viewer#214]
After upgrading to Android 7.0 Nougat on my Nexus 6P, the app can no longer be launched. As can be seen in the screenshot below, the error message "Document Viewer keeps stopping" pops up, prompting the user to close the app.

![screenshot_20160924-234004](https://cloud.githubusercontent.com/assets/11317451/18809628/937ef412-82b3-11e6-8649-dfc7f82f7e1b.png)
Let me know if any further information / log is required for debugging purposes.

![screenshot_20160924-234716](https://cloud.githubusercontent.com/assets/11317451/18809629/95c83a9e-82b3-11e6-9c03-22749e19e08d.png)

Although I've included my device info above, this problem is unlikely to be specific to my device, but rather it should affect all devices running Android 7.0, the number of which will soon start to expand. Therefore, please consider adding support for Android 7.0.

**Comment by ericwa** [comment]
Thanks.. did you install from Google Play?

There was a previous report of crash on launch on 7.0: https://github.com/SufficientlySecure/document-viewer/issues/191 , it's fixed in the [latest release on F-Droid](https://f-droid.org/repository/browse/?fdid=org.sufficientlysecure.viewer) (v2.7.7)

**Comment by xiatianyu** [comment]
Thank you for your advice. I installed the app from F-Droid but for some strange reason, F-Droid was showing 2.7.4 as the least version even though I updated its repos… Now, after clearing all its cache and data in the settings, F-Droid went back to normal and I was able to install Version 2.7.7. The problem is fixed now with the update.
