### ISSUE TITLE
there was some error when ,i was intialized ndk-build command in project

### ISSUE THREAD

**Issue by pawarlalit29** [SufficientlySecure/document-viewer#221]
there was some error when i was intialized ndk-build command in project

error: Could not find incbin file 'resources/fonts/urw/NimbusMono-Regular.cff'
.incbin "resources/fonts/urw/NimbusMono-Regular.cff"

**Comment by ericwa** [comment]
Thanks! It's fixed in c18d79a399a39985b1bd9e7c0c74ab18e9fd1d9f; you'll need to run `init.sh` again.
