### ISSUE TITLE
First attempt at Configure Taps after deleting all fails

### ISSUE THREAD

**Issue by JohnVeness** [SufficientlySecure/document-viewer#226]
Steps to reproduce:
1 Go into Configure Taps
2 Repeatedly press Delete until all regions deleted
3 Drag highlight a region
4 Assign an action, e.g. Single Tap does Find Text
5 Press Back
6 Attempt the action, doesn't eork
7 Go back into Configure Taps, observe no regions defined

DV 2.7.8

**Comment by JohnVeness** [comment]
Actually, I've found more generally that the Configure Taps editor doesn't always seem to save changes.

**Comment by ericwa** [comment]
I reproduced it too; it seems to randomly save sometimes and not other times. Need to check in the debugger..

**Comment by ericwa** [comment]
Closing the dialog was making it so any further changes (dragging to add a touch region) wouldn't be saved, unless you leave the "configure taps" screen completely.
I think I fixed it.
