### ISSUE TITLE
unable to copy text PDF file

### ISSUE THREAD

**Issue by krihsna** [SufficientlySecure/document-viewer#232]
2.7.9
android 5.1 w/out play store
ls-4001/lyf

i am unable to copy text from PDF file, the file is available at [z]. by default we can't copy text in pdf ? i couldn't find anything in settings, or did i overlook something ?

please excuse for not uploading file to any site, i am on extremely inconsistent 2g mobile data network.

[z] http://self.gutenberg.org/eBooks/WPLBN0001235287-Mindgames-by-Sam-Vaknin-Ph-D-.aspx?

**Comment by ericwa** [comment]
Sorry, it's just not implemented, we have a feature request for it though: https://github.com/SufficientlySecure/document-viewer/issues/93
