### ISSUE TITLE
Small lag with scrolling

### ISSUE THREAD

**Issue by LmarLoe** [SufficientlySecure/document-viewer#243]
I found annoying behavior while reading.
Scrolling begins not smoothly

Tap and then scroll slowly, on the beginning, text dashes on about one string.
At other times it mooves smooth  
Without lifting a finger this doesn't happen. This is not noticeable with fast scrolling.
This effect extends to all types of documents

It's seems that program awaits actions of double taps or swipes, even if taps are disabled in options and taps zones are off
Also if long tap applied, scrolling does not happen, this may some how related.

**Comment by ericwa** [comment]
Yep, I notice this too, agree this is annoying.
I think this is a duplicate: https://github.com/SufficientlySecure/document-viewer/issues/16
