### ISSUE TITLE
"Single page" view settings too hidden

### ISSUE THREAD

**Issue by a--v--k** [SufficientlySecure/document-viewer#25]
https://code.google.com/p/ebookdroid/issues/detail?id=505

What steps will reproduce the problem?
1. Be a noob
2. Download ebookdroid, and read in the description "We do have page turning emulation - just switch to single page mode and choose page turning effect of your choice!"
3. Try to find "single page mode"

What is the expected output?
This should be very easy to find.
I would expect it to be under the "magnifying glass (?)" icon, that has "full screen" "Show title", etc.

What do you see instead?
This setting is hidden very deeply.
All Setting - makes sense, though a direct view mode menu would be better
Rendering  - not really the place I'd expect this setting. Rendering sounds more like issues about fonts and stuff.
Document View mode - makes sense. But it is the 5th option down, so one has to read fairly carefully.

It is also available in Book settings, and there is a bit less hidden. But the noob (me) is looking to have ALL books behave in a certain way

What version of the product are you using?
1.6.6

On what operating system?
Android 4.1.2

What device are you using?
Galaxy Note 2

Please provide any additional information below.
May 14, 2013 Delete comment #1 mlachmann

**Comment by ericwa** [comment]
I've found I want to enable or disable "Single Page" quite often. I tried adding it to the toolbar menu, like this:
![screen](https://cloud.githubusercontent.com/assets/239161/18238339/2f548c82-72f9-11e6-848e-eb479c46a018.png)

**Comment by ericwa** [comment]
I think this is fixed with the new Single Page toolbar item. For the actual page curl settings you still need to go into Book Settings.
