### ISSUE TITLE
ebookdroid not offered as an app to open ePUB links

### ISSUE THREAD

**Issue by a--v--k** [SufficientlySecure/document-viewer#27]
https://code.google.com/p/ebookdroid/issues/detail?id=517

In my Android FireFox browser, I'm clicking on a link to:

http://archive.org/download/WarIsARacket/WarIsARacket.epub

Host page is http://archive.org/details/WarIsARacket

I don't get an option to open it with ebookdroid (only Adobe reader and some other readers I had downloaded to try them out).

I'm using a Samsung Galaxy S3 with Android 4.1.2

**Comment by KrasnayaPloshchad** [comment]
Oh~well, I found an ePub rendering engine, you can use this engine to implenting ePub support through invoking native Web browsing engine.
https://github.com/fluid-project/EPUB

This link contain some websites which provide DRM-free ePub books for test if you want to launch a plan on adding ePub support:
http://www.epubread.com/ebooks.php
