### ISSUE TITLE
Project seems abandoned... Move along, folks.

### ISSUE THREAD

**Issue by W9JYD** [SufficientlySecure/document-viewer#320]
See my comment at issue #318 .

This project seems to be abandoned. No updates and serious issues have remained open with not a peep from the repo owner @dschuermann. 

Since this app is based upon mupdf, I will be installing the vanilla, upstream version which is in active development, instead.

Thus the sorry state of open source. Again, I say this without apology. Some open source projects are great--I use quite a few of them, and regularly, every day. 

I wish I knew modern programming languages so I could fork this and keep it updated, but I only know BASIC (the Tandy Color Computer Extended dialect... Don't laugh) and enough HTML, CSS and PHP because I run a WordPress site which takes most of my time.

Thanks @dschuermann for a good app but if you moved on, I'd recommend that this repo be read only and someone can hopefully take it over.

73 de W9JYD

**Comment by matsievskiysv** [comment]
I've [forked this project](https://gitlab.com/matsievskiysv/book-reader) and changed it a bit (updated libs etc). I will request adding it to [f-droid](https://f-droid.org/) if @dschuermann won't mind or will not reply.

**Comment by dschuermann** [comment]
@matsievskiysv sure I am always happy if someone takes ownership. You also invited you to this github repo, but do however you like, this is open source :)

**Comment by hwasiti** [comment]
Thanks @dschuermann and @matsievskiysv
Finally, somebody could take ownership. I can see my pull request merged after 1 year.

**Comment by matsievskiysv** [comment]
@dschuermann How exactly f-droid pulls new releases? Does it detect changes to master?

**Comment by ildar** [comment]
New tags mainly. Maybe some manual work to be done

**Comment by ericwa** [comment]
@matsievskiysv 

> How exactly f-droid pulls new releases? Does it detect changes to master?

When I was doing releases I had to:

- Tag a version in this repo
- Update the metadata file https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.sufficientlysecure.viewer.yml
- Make a merge request on https://gitlab.com/fdroid/fdroiddata 

Typically it would take a few days for the update to show up in f-droid (sometimes the build would fail)

**Comment by matsievskiysv** [comment]
@ericwa Maybe you know why compilation config of the package is different for [each architecture](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.sufficientlysecure.viewer.yml#L1413-1572)? Is this a f-droid thing or maybe an old gradle version?

**Comment by matsievskiysv** [comment]
> @ericwa Maybe you know why compilation config of the package is different for [each architecture](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.sufficientlysecure.viewer.yml#L1413-1572)? Is this a f-droid thing or maybe an old gradle version?

Found the answer:  https://gitlab.com/fdroid/fdroiddata/-/issues/2115
