### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [SufficientlySecure/document-viewer#325]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by rbrito** [comment]
Why was it closed? How was it solved (or not solved)? The page https://f-droid.org/en/packages/org.sufficientlysecure.viewer/ doesn't seem to have any screenshots...

Please, when closing issues, comment on why it is being closed!

**Comment by mondlicht-und-sterne** [comment]
It was only an information for you...

**Comment by Korb** [comment]
There are still no screenshots on the [application page.](https://f-droid.org/packages/org.sufficientlysecure.viewer/):

![Document Viewer](https://user-images.githubusercontent.com/3509797/222921722-037aa1fd-dad1-499a-bbb0-54a8cbce25ef.jpg)
