### ISSUE TITLE
Add support for Samsung Multi-Window and Pen-Window

### ISSUE THREAD

**Issue by sarimak** [sufficientlysecure/document-viewer#46]
Please add a few lines to the AndroidManifest to enable support for these Samsung-specific features.

HOWTO + links to the docs + link to Osmand's working implementation of one of thes features: https://f-droid.org/forums/topic/request-add-support-for-samsung-multi-window/

I can test a custom APK on SGS3, Note8 and Note10.1 2014 upon request.

**Comment by ortylp** [comment]
+1

**Comment by sarimak** [comment]
Thank you! The multi-window feature works great on my Note 10.1 2014.
