### ISSUE TITLE
PDF Problem: Bad anti-aliased rendering

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [sufficientlysecure/document-viewer#61]
I've a problem with the attached pdf, it feels rendering badly for anti-aliasing when open with Document Viewer.

Name:
Libertine’s XeTex-Documentation
Link:

**Comment by KrasnayaPloshchad** [comment]
http://www.linuxlibertine.org/index.php?id=89&L=1

**Comment by tuxor1337** [comment]
Do you mean http://www.linuxlibertine.org/fileadmin/user_upload/PDF/Libertine-XeTex-DE.pdf or http://www.linuxlibertine.org/fileadmin/user_upload/PDF/Multilingual.pdf ?

By the way, I can't see any rendering problems with either one...

**Comment by KrasnayaPloshchad** [comment]
I mean http://www.linuxlibertine.org/fileadmin/user_upload/PDF/Libertine-XeTex-EN.pdf

I can see this problem when I move into removable sdcard.

**Comment by tuxor1337** [comment]
Still, viewing this file will not produce any rendering problems for me. Moving it to the removable sdcard still doesn't change anything. Which version of Android are you using and which smartphone?

**Comment by KrasnayaPloshchad** [comment]
Coolpad 5310, Android 4.3

**Comment by tuxor1337** [comment]
Can you reproduce it with any other Android device?

**Comment by KrasnayaPloshchad** [comment]
Well, I have a Lenovo device, I tried to open these file with DV just now, but it looks worksforme, I think it is resolved.
