### ISSUE TITLE
[suggestion] Get rid of the creepy bookshelf

### ISSUE THREAD

**Issue by ghost** [sufficientlysecure/document-viewer#85]
It frightens the children...

![screenshot_2015-04-10-16-16-49](https://cloud.githubusercontent.com/assets/11886052/7096325/2ce8e074-df9d-11e4-869c-fdceebc1191b.png)

**Comment by tuxor1337** [comment]
You serious?

**Comment by tedthqme** [comment]
It's only my opinion. The rest of the app is great, it's just this design that seems incongruous.

**Comment by tuxor1337** [comment]
Closing this, since I don't get the point. Reopen with explicit proposals for what to change if you think that this is an issue.
