### ISSUE TITLE
MuPDF library 1.7 released

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [sufficientlysecure/document-viewer#86]
Hi,

The MuPDF website pressed a news that they are released version 1.7, I think DV should update with this library because I think this is a big update. The following content is copied from thier news page.

```
Headline changes:

    New 'Indie dev' licensing options - contact sales@artifex.com for more details.
    New HTML layout engine, and (DRM-free) EPUB viewer.
    Reduced memory usage - displaylists and internal PDF representation take much less memory, reducing total memory use on some files by over 60%. 

Important API changes:

    Bound contexts have been removed; we now pass fz_contexts explicitly.
    Reference counting of paths and text structures. 

Features:

    Add mutool pages option.
    Tweaked rendering to prevent feature dropout in common cases.
    Viewer tweaks
        Better mouse wheel handling
        Shift-space support
        Mouse button control of presentation mode
        Failed reloads do not close document 

Internal changes:

    PDF filter revamp - simpler interface.
    Devices use derived structures rather than user pointer.
    Sparse PDF xrefs held in more compact form.
    New gsview viewer split out to its own repository. 

Bug fixes

    Improved handling of broken files.
    Fix BBoxes of Type 3 fonts.
    Updated fonts (including greek and cyrillic).
    Various memory leaks and crashes.
    And many more.
```
By the way, the preview release can support CBZ natively.

**Comment by tuxor1337** [comment]
Updating the integrated mupdf library is probably as easy as rebuilding document-viewer. But I think you are heading at something else...?

EPUB and CBZ support in MuPdf is nice, but you should be aware that there is still a lot of effort involved in forwarding this support to document-viewer. It's almost as much as it would be to integrate CBZ and EPUB support via any other library, because the respective code has to be integrated manually via JNI.

**Comment by KrasnayaPloshchad** [comment]
I understand it, but I think it is worth a try.

**Comment by tuxor1337** [comment]
Okay, have you tried the MuPdf app for android and have you seen it's EPUB support? In my opinion that kind of EPUB support is more or less like converting EPUB to PDF and then displaying it on screen. If that is what you want - that should be doable.

**Comment by KrasnayaPloshchad** [comment]
Well, I remembered EPUBreader website [recommend](http://www.epubread.com/ebooks.php) several sites that you can get EPUB freely, I downloaded several EPUB file from there, next I opened with MuPDF, found it is really support this format, then I found a CBZ file from [here](https://github.com/harrypujols/website/blob/master/downloads/venus_butterfly.cbz) to test, it was great.

**Comment by tuxor1337** [comment]
Okay, so is it just me or does Document Viewer claim to support CBZ at the moment but can't actually open any CBZ files?

**Comment by KrasnayaPloshchad** [comment]
Well, I got two CBZ files from [here](https://github.com/harrypujols/website/tree/master/downloads), all of them cannot open with Document Viewer.

**Comment by tuxor1337** [comment]
Okay, you convinced me. I'm going to have a look into CBZ and EPUB support ;)

**Comment by tuxor1337** [comment]
I tried simply adding contexts for CBZ and EPUB just the same way the XpsContext works at the moment. For CBZ this worked fine. But for EPUB libmupdf throws strange warnings ("invalid key in dict" and "cannot parse dict" or "ignoring invalid character in hex string") and errors and nothing is displayed on the screen as if the document was empty.

The very same epub file opens fine in the MuPdf app and I wasn't able to find out what it is that they do differently in their jni-code :-/

**Comment by tuxor1337** [comment]
The MuPdf library is up to date now. CBZ and EPUB support from MuPdf work fine now. I removed the cbx code completely.
