### ISSUE TITLE
File Browser settings does not include epub file type

### ISSUE THREAD

**Issue by snelltheta** [sufficientlysecure/document-viewer#90]
Since epub support was added, this needs to be updated

**Comment by tuxor1337** [comment]
Okay, that's easy. The affected preference is called `@string/pref_brfiletypes` and here are the affected source code files:
document-viewer/src/main/res/xml/fragment_browser.xml
document-viewer/src/main/res/xml-v14/fragment_browser.xml
document-viewer/src/main/res/values-{LANG}/strings_preferences_browser.xml
Feel free to fix this yourself, I don't have time for this at the moment.
