### ISSUE TITLE
Update compileSdkVersion version 22 not show actionBar

### ISSUE THREAD

**Issue by sunyuyangg555** [sufficientlysecure/document-viewer#92]
when I update    compileSdkVersion 19 to 22, not show menus on the top.

**Comment by tuxor1337** [comment]
Why do you want to set compileSdkVersion to 22? Apart from that, I can assure you that the whole UI is one big patchwork. Almost no official Android UI elements are being used and every SDK version has its own huge set of settings and patches. It would be a relieve if someone started to unify and simplify the UI across all SDK versions.

**Comment by sunyuyangg555** [comment]
Thanks your reply very much! I let AbstractActionActivity extends ActionBarActivity . It can show now.I want to use material UI. My English is not so good,  Please forgive me,

**Comment by tuxor1337** [comment]
Hm, I'm not quite sure I understand what you are saying. But if you have improvements to the UI pull requests are very welcome!

**Comment by tuxor1337** [comment]
We don't experience any issues with pull request #99. If you don't mind I'm closing this. But if you still run into problems with the new SDK version, feel free to reopen with a description of your problem.

**Comment by sunyuyangg555** [comment]
Thinks, I will clone the new version.
