### ISSUE TITLE
GLES configuration on Onyx Boox M96

### ISSUE THREAD

**Issue by asd-and-Rizzo** [SufficientlySecure/document-viewer#94]
Cannot open pdf with `our device cannot support required GLES configuration` error on Onyx Boox M96 e-ink reader.

Latest application from f-droid.

**Comment by tuxor1337** [comment]
That's a pity, because for me it works like a charm on my 6 inch Eink reader Icarus Illumina (E653).

**Comment by timofonic** [comment]
@tuxor1337 Congratulations!

But there are unlucky Onyx Boox M96 users. Many of us need a big screen because our eyes get tired easily.

So are eink devices into consideration? I understand if not.

**Comment by ericwa** [comment]
There is hope, this error message means `eglChooseConfig` didn't return any configs matching the specifications document-viewer gave:
```
    private final int mConfigSpec[] = new int[] { EGL10.EGL_RED_SIZE, 5, EGL10.EGL_GREEN_SIZE, 6, EGL10.EGL_BLUE_SIZE,
            5, EGL10.EGL_ALPHA_SIZE, 0, EGL10.EGL_STENCIL_SIZE, GLConfiguration.stencilRequired ? 1 : 0, EGL10.EGL_NONE };
```

I found an app called "OpenGL-ES Info" that seems to list the supported configs. Can someone with an Onyx install this: https://play.google.com/store/apps/details?id=nl.svdree.glesinfo&hl=en
and upload the report it generates?

**Comment by asd-and-Rizzo** [comment]
1.4 version of program shows next:

![20160213_151604](https://cloud.githubusercontent.com/assets/757125/13027617/b6101446-d266-11e5-8a28-7cf6c63b7b6f.jpg)
![20160213_151617](https://cloud.githubusercontent.com/assets/757125/13027618/b6481b0c-d266-11e5-844e-e568ee6a3f2b.jpg)
![20160213_151628](https://cloud.githubusercontent.com/assets/757125/13027619/b64a25f0-d266-11e5-97ee-ddb03cdc4e57.jpg)

**Comment by ericwa** [comment]
@asd-and-Rizzo thanks, that helps! 

The info is very similar to what I get when I run the app on the API8 emulator image, which is using the pixelflinger software GLES implementation. In particular, there are no configs with Stencil support. I'm betting this ebook reader is using pixelflinger as well, although unfortunately the vendor/version/renderer labels aren't displaying.

Interestingly, document-viewer has a hack for running in the emulator: 
`GLConfiguration.stencilRequired = !IS_EMULATOR;`

We probably just need to remove this, and not require stencil. Everything seems to work OK on the emulator with no stencil buffer so I'm not sure why it was required

**Comment by ericwa** [comment]
@asd-and-Rizzo @timofonic The 2.7.4 release is available in F-Droid now, it has a fix which I'm hoping will allow document-viewer to work on the Onyx boox.
