### ISSUE TITLE
Default interface is not e-ink friendly

### ISSUE THREAD

**Issue by asd-and-Rizzo** [SufficientlySecure/document-viewer#95]
Main book choosing interface on Onyx Boox M96 not very good. Top bar buttons are not clearly visible and shelve background looks bad.

**Comment by tuxor1337** [comment]
On my eink device (Icarus Illumina E653) it looks fine. The top bar buttons are clearly visible and the shelve background just looks the same as always (just in b/w).

Maybe it's easier to understand what you are talking about if you take a photo of your device showing the relevant parts of the UI.

**Comment by Sanjib1** [comment]
Ok

**Comment by tuxor1337** [comment]
Closing this as works for me.
